# Generated by Django 5.2 on 2025-04-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
        ('products', '0002_product_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.merchant'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.provider'),
        ),
    ]
