# Generated by Django 5.2 on 2025-04-27 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_provider_id_product_merchant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOptionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('option_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.optiontype')),
            ],
            options={
                'verbose_name': 'Обязательная опция категория',
                'verbose_name_plural': 'Обязательные опции категорий',
            },
        ),
    ]
