# Generated by Django 5.2 on 2025-05-04 07:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_brand_productvariant_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
    ]
