# Generated by Django 5.2 on 2025-05-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
