# Generated by Django 5.2 on 2025-05-20 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantoption',
            name='option_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.optionvalue'),
        ),
    ]
