# Generated by Django 5.2 on 2025-05-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_variantoption_option_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='provider_sku',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
