# Generated by Django 5.2 on 2025-05-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
