# Generated by Django 5.2 on 2025-05-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productvariant_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_service',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='source_service',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
