# Generated by Django 5.2 on 2025-05-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stock_id',
            field=models.UUIDField(null=True),
        ),
    ]
