# Generated by Django 5.2 on 2025-05-27 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_alter_merchant_provider_alter_merchant_user'),
        ('orders', '0003_alter_order_stock_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stock_id',
            new_name='stock_task_id',
        ),
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('ready_to_shipment', 'Ready To Shipment'), ('in_way', 'In Way'), ('delivered', 'Delivered')], default='new', max_length=255),
        ),
    ]
