# Generated by Django 5.2 on 2025-06-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipped_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
